### ISSUE TITLE
CDVer1 -Travel maps not loading over https 

### ISSUE THREAD

**Issue by BuildingCityDashboards** [BuildingCityDashboards/bcd-cd-v2.0#3]
Map will not load over a secure connection i.e. https://corkdashboard.ie/pages/CorkTravel

Possibly related- issue #2
Mixed Content: The page at 'https://corkdashboard.ie/pages/index' was loaded over HTTPS, but requested an insecure script 'http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js'. This request has been blocked; the content must be served over HTTPS.

Fix:
Changed versions of Leaflet and loaded securely. Files affected- pages/ travel_map.ctp and environment_map.ctp

**Comment by BashirShalaik** [comment]
Solved using unpkg.com Delivery network services

**Comment by BashirShalaik** [comment]
Solved using unpkg.com Delivery network services
